-- ============================================================
-- 54 недельные главы Торы (паршийот) для существующей таблицы
-- public.bible_verses из add_synodal_bible.sql
--
-- Сопоставление с текстом делается НЕ по book_code, а по:
--   book_order + chapter + verse
--
-- Это позволяет не зависеть от того, как именно у вас названы
-- коды книг (GEN / Genesis / Быт и т.п.).
-- ============================================================

-- 1) Таблица границ недельных глав
create table if not exists public.torah_portions (
  id bigint generated by default as identity primary key,

  portion_number smallint not null unique
    check (portion_number between 1 and 54),

  name_en text not null,
  name_he text not null,
  name_ru text not null,

  -- 1=Бытие, 2=Исход, 3=Левит, 4=Числа, 5=Второзаконие
  book_order smallint not null
    check (book_order between 1 and 5),

  -- Не используется для JOIN; оставлено как читаемая метаинформация.
  book_code text not null,

  start_chapter smallint not null check (start_chapter > 0),
  start_verse   smallint not null check (start_verse > 0),
  end_chapter   smallint not null check (end_chapter > 0),
  end_verse     smallint not null check (end_verse > 0),

  created_at timestamptz not null default now(),

  unique (book_order, start_chapter, start_verse)
);

-- На случай, если ранее была создана версия torah_portions без book_order.
alter table public.torah_portions
  add column if not exists book_order smallint;

-- Если колонка добавилась в старую таблицу, наполним ее по стандартному book_code.
update public.torah_portions
set book_order = case book_code
  when 'Genesis' then 1
  when 'Exodus' then 2
  when 'Leviticus' then 3
  when 'Numbers' then 4
  when 'Deuteronomy' then 5
  else book_order
end
where book_order is null;

create index if not exists torah_portions_start_idx
  on public.torah_portions (book_order, start_chapter, start_verse);

create index if not exists torah_portions_end_idx
  on public.torah_portions (book_order, end_chapter, end_verse);


-- 2) Все 54 парши
insert into public.torah_portions
  (
    portion_number,
    name_en,
    name_he,
    name_ru,
    book_order,
    book_code,
    start_chapter,
    start_verse,
    end_chapter,
    end_verse
  )
values
  -- БЫТИЕ / GENESIS
  (1,  'Bereshit',         'בְּרֵאשִׁית',       'Берешит',        1, 'Genesis',      1,  1,  6,  8),
  (2,  'Noach',            'נֹחַ',              'Ноах',           1, 'Genesis',      6,  9, 11, 32),
  (3,  'Lech-Lecha',       'לֶךְ-לְךָ',         'Лех-Леха',       1, 'Genesis',     12,  1, 17, 27),
  (4,  'Vayera',           'וַיֵּרָא',           'Вайера',         1, 'Genesis',     18,  1, 22, 24),
  (5,  'Chayei Sara',      'חַיֵּי שָׂרָה',      'Хаей Сара',      1, 'Genesis',     23,  1, 25, 18),
  (6,  'Toldot',           'תּוֹלְדֹת',          'Толдот',         1, 'Genesis',     25, 19, 28,  9),
  (7,  'Vayetzei',         'וַיֵּצֵא',           'Вайеце',         1, 'Genesis',     28, 10, 32,  3),
  (8,  'Vayishlach',       'וַיִּשְׁלַח',        'Вайишлах',       1, 'Genesis',     32,  4, 36, 43),
  (9,  'Vayeshev',         'וַיֵּשֶׁב',          'Вайешев',        1, 'Genesis',     37,  1, 40, 23),
  (10, 'Miketz',           'מִקֵּץ',             'Микец',          1, 'Genesis',     41,  1, 44, 17),
  (11, 'Vayigash',         'וַיִּגַּשׁ',         'Вайигаш',        1, 'Genesis',     44, 18, 47, 27),
  (12, 'Vayechi',          'וַיְחִי',            'Вайехи',         1, 'Genesis',     47, 28, 50, 26),

  -- ИСХОД / EXODUS
  (13, 'Shemot',           'שְׁמוֹת',            'Шмот',           2, 'Exodus',       1,  1,  6,  1),
  (14, 'Vaera',            'וָאֵרָא',            'Ваэра',          2, 'Exodus',       6,  2,  9, 35),
  (15, 'Bo',               'בֹּא',               'Бо',             2, 'Exodus',      10,  1, 13, 16),
  (16, 'Beshalach',        'בְּשַׁלַּח',         'Бешалах',        2, 'Exodus',      13, 17, 17, 16),
  (17, 'Yitro',            'יִתְרוֹ',            'Итро',           2, 'Exodus',      18,  1, 20, 23),
  (18, 'Mishpatim',        'מִּשְׁפָּטִים',       'Мишпатим',       2, 'Exodus',      21,  1, 24, 18),
  (19, 'Terumah',          'תְּרוּמָה',          'Трума',          2, 'Exodus',      25,  1, 27, 19),
  (20, 'Tetzaveh',         'תְּצַוֶּה',          'Тецаве',         2, 'Exodus',      27, 20, 30, 10),
  (21, 'Ki Tisa',          'כִּי תִשָּׂא',       'Ки Тиса',        2, 'Exodus',      30, 11, 34, 35),
  (22, 'Vayakhel',         'וַיַּקְהֵל',         'Ваякхель',       2, 'Exodus',      35,  1, 38, 20),
  (23, 'Pekudei',          'פְקוּדֵי',           'Пкудей',         2, 'Exodus',      38, 21, 40, 38),

  -- ЛЕВИТ / LEVITICUS
  (24, 'Vayikra',          'וַיִּקְרָא',         'Ваикра',         3, 'Leviticus',    1,  1,  5, 26),
  (25, 'Tzav',             'צַו',                'Цав',            3, 'Leviticus',    6,  1,  8, 36),
  (26, 'Shmini',           'שְּׁמִינִי',          'Шмини',          3, 'Leviticus',    9,  1, 11, 47),
  (27, 'Tazria',           'תַזְרִיעַ',          'Тазриа',         3, 'Leviticus',   12,  1, 13, 59),
  (28, 'Metzora',          'מְּצֹרָע',           'Мецора',         3, 'Leviticus',   14,  1, 15, 33),
  (29, 'Achrei Mot',       'אַחֲרֵי מוֹת',       'Ахарей Мот',     3, 'Leviticus',   16,  1, 18, 30),
  (30, 'Kedoshim',         'קְדֹשִׁים',          'Кдошим',         3, 'Leviticus',   19,  1, 20, 27),
  (31, 'Emor',             'אֱמֹר',              'Эмор',           3, 'Leviticus',   21,  1, 24, 23),
  (32, 'Behar',            'בְּהַר',             'Бехар',          3, 'Leviticus',   25,  1, 26,  2),
  (33, 'Bechukotai',       'בְּחֻקֹּתַי',        'Бехукотай',      3, 'Leviticus',   26,  3, 27, 34),

  -- ЧИСЛА / NUMBERS
  (34, 'Bamidbar',         'בְּמִדְבַּר',        'Бемидбар',       4, 'Numbers',      1,  1,  4, 20),
  (35, 'Nasso',            'נָשֹׂא',             'Насо',           4, 'Numbers',      4, 21,  7, 89),
  (36, 'Beha’alotcha',     'בְּהַעֲלֹתְךָ',      'Беаалотха',      4, 'Numbers',      8,  1, 12, 16),
  (37, 'Sh’lach',          'שְׁלַח-לְךָ',        'Шлах',           4, 'Numbers',     13,  1, 15, 41),
  (38, 'Korach',           'קֹרַח',              'Корах',          4, 'Numbers',     16,  1, 18, 32),
  (39, 'Chukat',           'חֻקַּת',             'Хукат',          4, 'Numbers',     19,  1, 22,  1),
  (40, 'Balak',            'בָּלָק',             'Балак',          4, 'Numbers',     22,  2, 25,  9),
  (41, 'Pinchas',          'פִּינְחָס',          'Пинхас',         4, 'Numbers',     25, 10, 30,  1),
  (42, 'Matot',            'מַּטּוֹת',           'Матот',          4, 'Numbers',     30,  2, 32, 42),
  (43, 'Masei',            'מַסְעֵי',            'Масей',          4, 'Numbers',     33,  1, 36, 13),

  -- ВТОРОЗАКОНИЕ / DEUTERONOMY
  (44, 'Devarim',          'דְּבָרִים',          'Дварим',         5, 'Deuteronomy',  1,  1,  3, 22),
  (45, 'Vaetchanan',       'וָאֶתְחַנַּן',       'Ваэтханан',      5, 'Deuteronomy',  3, 23,  7, 11),
  (46, 'Eikev',            'עֵקֶב',              'Экев',           5, 'Deuteronomy',  7, 12, 11, 25),
  (47, 'Re’eh',            'רְאֵה',              'Реэ',            5, 'Deuteronomy', 11, 26, 16, 17),
  (48, 'Shoftim',          'שֹׁפְטִים',          'Шофтим',         5, 'Deuteronomy', 16, 18, 21,  9),
  (49, 'Ki Teitzei',       'כִּי-תֵצֵא',         'Ки Теце',        5, 'Deuteronomy', 21, 10, 25, 19),
  (50, 'Ki Tavo',          'כִּי-תָבוֹא',        'Ки Таво',        5, 'Deuteronomy', 26,  1, 29,  8),
  (51, 'Nitzavim',         'נִצָּבִים',          'Ницавим',        5, 'Deuteronomy', 29,  9, 30, 20),
  (52, 'Vayeilech',        'וַיֵּלֶךְ',          'Вайелех',        5, 'Deuteronomy', 31,  1, 31, 30),
  (53, 'Ha’azinu',         'הַאֲזִינוּ',         'Аазину',         5, 'Deuteronomy', 32,  1, 32, 52),
  (54, 'Vezot Haberakhah', 'וְזֹאת הַבְּרָכָה', 'Везот а-Браха',  5, 'Deuteronomy', 33,  1, 34, 12)

on conflict (portion_number) do update
set
  name_en       = excluded.name_en,
  name_he       = excluded.name_he,
  name_ru       = excluded.name_ru,
  book_order    = excluded.book_order,
  book_code     = excluded.book_code,
  start_chapter = excluded.start_chapter,
  start_verse   = excluded.start_verse,
  end_chapter   = excluded.end_chapter,
  end_verse     = excluded.end_verse;


-- 3) RLS: названия и границы паршийот можно читать всем,
--    аналогично bible_verses.
alter table public.torah_portions enable row level security;

drop policy if exists "torah_portions_read" on public.torah_portions;
create policy "torah_portions_read"
  on public.torah_portions
  for select
  to anon, authenticated
  using (true);


-- 4) Представление для фронтенда.
-- Для каждого стиха:
--   start_portion_* заполнено, если ПЕРЕД ним начинается новая парша;
--   end_portion_* заполнено, если ПОСЛЕ него заканчивается парша.
--
-- security_invoker=true заставляет view соблюдать RLS исходных таблиц.
drop view if exists public.bible_verses_with_torah_markers;

create view public.bible_verses_with_torah_markers
with (security_invoker = true)
as
select
  v.*,

  ps.id               as start_portion_id,
  ps.portion_number   as start_portion_number,
  ps.name_ru          as start_portion_name_ru,
  ps.name_en          as start_portion_name_en,
  ps.name_he          as start_portion_name_he,
  ps.start_chapter    as start_portion_chapter,
  ps.start_verse      as start_portion_verse,
  ps.end_chapter      as start_portion_end_chapter,
  ps.end_verse        as start_portion_end_verse,

  pe.id               as end_portion_id,
  pe.portion_number   as end_portion_number,
  pe.name_ru          as end_portion_name_ru,
  pe.name_en          as end_portion_name_en,
  pe.name_he          as end_portion_name_he

from public.bible_verses v

left join public.torah_portions ps
  on ps.book_order    = v.book_order
 and ps.start_chapter = v.chapter
 and ps.start_verse   = v.verse

left join public.torah_portions pe
  on pe.book_order  = v.book_order
 and pe.end_chapter = v.chapter
 and pe.end_verse   = v.verse;


-- ============================================================
-- 5) ПРОВЕРКИ ПОСЛЕ ЗАПУСКА
-- ============================================================

-- Должно вернуть 54.
select count(*) as torah_portions_count
from public.torah_portions;


-- Проверяем, что КАЖДАЯ точка начала действительно существует
-- среди стихов вашей Синодальной Библии.
-- В идеале запрос возвращает 0 строк.
select
  p.portion_number,
  p.name_ru,
  p.book_order,
  p.start_chapter,
  p.start_verse
from public.torah_portions p
left join public.bible_verses v
  on v.book_order = p.book_order
 and v.chapter    = p.start_chapter
 and v.verse      = p.start_verse
where v.id is null
order by p.portion_number;


-- Проверяем точки окончания.
-- В идеале также 0 строк.
select
  p.portion_number,
  p.name_ru,
  p.book_order,
  p.end_chapter,
  p.end_verse
from public.torah_portions p
left join public.bible_verses v
  on v.book_order = p.book_order
 and v.chapter    = p.end_chapter
 and v.verse      = p.end_verse
where v.id is null
order by p.portion_number;


-- Пример: посмотреть все места начала паршийот прямо в тексте.
select
  book_name,
  chapter,
  verse,
  start_portion_number,
  start_portion_name_ru,
  start_portion_name_he,
  start_portion_name_en
from public.bible_verses_with_torah_markers
where start_portion_id is not null
order by book_order, chapter, verse;


-- ============================================================
-- 6) ПРИМЕР ЗАПРОСА ИЗ SUPABASE / FRONTEND
-- ============================================================
--
-- const { data, error } = await supabase
--   .from('bible_verses_with_torah_markers')
--   .select('*')
--   .eq('book_order', 1)
--   .eq('chapter', 25)
--   .order('verse');
--
-- В React:
--
-- {verses.map((verse) => (
--   <Fragment key={verse.id}>
--     {verse.start_portion_id && (
--       <TorahPortionDivider
--         number={verse.start_portion_number}
--         nameRu={verse.start_portion_name_ru}
--         nameHe={verse.start_portion_name_he}
--         nameEn={verse.start_portion_name_en}
--         range={`${verse.start_portion_chapter}:${verse.start_portion_verse}–${verse.start_portion_end_chapter}:${verse.start_portion_end_verse}`}
--       />
--     )}
--
--     <Verse verse={verse} />
--   </Fragment>
-- ))}
